/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.betancur.view;

import javax.swing.JPanel;

/**
 *
 * @author Ariel
 */
public class ModuloPrincipal extends javax.swing.JPanel {
    PanelContenedor contenedorSingleton;
    ViewRegistrarCampo viewRegistrarCampo;
    
    /**
     * Creates new form ModuloPrincipal
     */
    public ModuloPrincipal() {
        initComponents();
        contenedorSingleton = PanelContenedor.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_registrarCampo = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(5, 1, 0, 10));

        jbtn_registrarCampo.setText("Registrar Campo");
        jbtn_registrarCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_registrarCampoActionPerformed(evt);
            }
        });
        add(jbtn_registrarCampo);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_registrarCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_registrarCampoActionPerformed
        viewRegistrarCampo = new ViewRegistrarCampo();
        
        contenedorSingleton.cargarModulo(viewRegistrarCampo);
        
    }//GEN-LAST:event_jbtn_registrarCampoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtn_registrarCampo;
    // End of variables declaration//GEN-END:variables

}
