/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.betancur.view;

import com.betancur.model.Campo;
import com.betancur.model.Lote;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ariel
 */
public class PanelRegistroConfirmacion extends javax.swing.JPanel {

    //utilizado para llamar al contenedor
    PanelContenedor contenedorSingleton;
    
    //Pantalla de inicio
    ModuloPrincipal moduloPrincipal;
    
    //modelo para la tabla
    DefaultTableModel modeloTablaLotes = new DefaultTableModel();
    
    private Campo nuevoCampo;
    
    /**
     * Creates new form PanelRegistroConfirmacion
     */
    public PanelRegistroConfirmacion() {
        
        initComponents();
        
        contenedorSingleton = PanelContenedor.getInstance();
        
        this.modeloTablaLotes.addColumn("N°");
        this.modeloTablaLotes.addColumn("Superficie");
        this.modeloTablaLotes.addColumn("Tipo de Suelo");
        
        this.jtbl_lotes.getTableHeader().setReorderingAllowed(false) ;
        this.jtbl_lotes.setModel(modeloTablaLotes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msj = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_lotes = new javax.swing.JTable();
        jbtn_aceptar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setLayout(null);
        add(msj);
        msj.setBounds(20, 14, 750, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Lotes");
        add(jLabel2);
        jLabel2.setBounds(20, 60, 57, 29);

        jtbl_lotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbl_lotes);

        add(jScrollPane1);
        jScrollPane1.setBounds(19, 95, 750, 402);

        jbtn_aceptar.setText("Aceptar");
        jbtn_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_aceptarActionPerformed(evt);
            }
        });
        add(jbtn_aceptar);
        jbtn_aceptar.setBounds(680, 540, 90, 23);
        add(jSeparator1);
        jSeparator1.setBounds(20, 579, 750, 10);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_aceptarActionPerformed
        moduloPrincipal = new ModuloPrincipal();
        contenedorSingleton.cargarModulo(moduloPrincipal);
    }//GEN-LAST:event_jbtn_aceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtn_aceptar;
    private javax.swing.JTable jtbl_lotes;
    private javax.swing.JLabel msj;
    // End of variables declaration//GEN-END:variables

    public void cargar(Campo c){
        
        //prepara el objeto a ser insertado en la tabla con los valores del lote
        Object []object = new Object[3];
        
        //Recorre todos los lotes del campo c, pasado como parametro
        //cada lote lo agrega al modelo de la tabla, como una nueva fila
        for (Lote listaDeLote : c.getListaDeLotes()) {
            object[0] = listaDeLote.getNumeroLote();
            object[1] = listaDeLote.getSuperficieLote(); 
            object[2] = listaDeLote.getTipoSuelo().getNumero(); 
            //Agrega datos del lote a la tabla
            modeloTablaLotes.addRow(object);
        }
        msj.setText("El Campo \"" +c.getNombreCampo()+"\" de "+c.getSuperficieCampo()+" ha ha sido registrado: ");
        
    }
}
